openapi: 3.0.1
info:
  title: '@jupiterone/whitehat Client'
  description: Whitehat REST API client
  x-cortex-git:
    github:
      repository: JupiterOne/whitehat-client
  x-cortex-owners:
    - type: group
      name: JupiterOne/sre
  x-cortex-tag: '@jupiterone/whitehat-client'
  x-cortex-service-groups:
    - tier-4
